// Generated by nitro

// App Config
import type { Defu } from 'defu'

import type { default as appConfig0 } from "/home/runner/work/dm-frontend-pwa/dm-frontend-pwa/src/packages/@core/ui/app.config";
import type { default as appConfig1 } from "/home/runner/work/dm-frontend-pwa/dm-frontend-pwa/src/node_modules/.pnpm/@nuxt+ui-pro@1.2.0_focus-trap@7.5.4_nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4._7ll53jb2dyqctfwpyetmpywaci/node_modules/@nuxt/ui-pro/app.config";

type UserAppConfig = Defu<{}, [typeof appConfig0, typeof appConfig1]>

declare module 'nitropack' {
  interface AppConfig extends UserAppConfig {}
}
    
export {}